resource_group_name     = "tfstate"
storage_account_name    = "tfstate81"
container_name          = "tfstate"
key                     = "terraform.tfstate"
access_key              = "DrsRJ+QwTg2jMbmzv8aKvtsqeZcTNU5/6xS4xAKDWWyKEs5bBGF3+vtdoJHQgN5sXmcz/dbgwhit+AStnHgFqw=="
